name: first_workflow

on: push

jobs:
    first_job:
       runs-on: ubuntu-latest
       steps:
       - name: Checkout Repo
         uses: actions/checkout@v4
       - name: Install Cowsay
         run: sudo apt-get install cowsay -y
       - name: Generate ASCII Artwork
         run: cowsay -f dragon "Run for cover, Monster Coming ...RAWR" >> dragon.txt  
       - name: test if File Exists
         run: find ~ -name dragon -type f -print
       - name: read file
         run: cat dragon.txt
       - name: list Repo Files
         run: ls -ltra
