name: Generate ASCII artwork

on:
    push
jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay program
          run: sudo apt-get install cowsay -y
        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, Dragon is coming...ROAR" >> dragon.txt
        - name: Upload Dragon file
          uses: actions/upload-artifact@v4
          with:
           name: dragon-text-file
           path: dragon.txt

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: Download Dragon text file
          uses: actions/download-artifact@v4
          with:
           name: dragon-text-file
        - name: Test File Exists
          run: find . -name dragon.* -type f | read

    deploy_job_3:
        needs: [test_job_2]
        runs-on: ubuntu-latest
        steps:
        - name: Download Dragon text file
          uses: actions/download-artifact@v4
          with:
           name: dragon-text-file
        - name: Read File
          run: cat dragon.txt
