name: Generate ASCII artwork

on:
    push
jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay program
          run: sudo apt-get install cowsay -y
        - name: Execute Cowsay CMD
          run: cowsay-f dragon "Run for cover, Dragon is coming...ROAR" >> dragon.txt
        - name: sleep for 15 sec
          run: sleep 15

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: sleep for 10 sec
          run: sleep 10
        - name: Test File Exists
          run: find ~ -name dragon -type f -print

    deploy_job_3:
        needs: [test_job_2]
        runs-on: ubuntu-latest
        steps:
        - name: Read File
          run: cat dragon.txt
        - name: Deploy
          run: echo 'Deploying ...'