name: matrix configutarion
on: [ push, workflow_dispatch]

jobs:
    deploy:
        strategy:
            fail-fast: false
            max-parallel: 3
            matrix:
                os: [ubuntu-latest, ubuntu-20.04, windows-latest]    
                images: [hello-world, alpine]
                exclude:
                - os: windows-latest
                  images: alpine
                include:
                - images: amd64/alpine
                  os: ubuntu-20.04
        runs-on: ${{ matrix.os}}
        steps:
        - name: Echo Docker details
          run: docker info
        - name: Run Image on ${{matrix.os}}
          run: docker run ${{matrix.images}} 